default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mysite_development
  username: armaine
  password: afXHXRhyjP9B5rJgL6b7tjtgvm6lEqlu
  # Assuming 'host' is the host name only, not the full URL
  host: dpg-clh0qlb1hq4c73fb3q6g-a.singapore-postgres.render.com

test:
  <<: *default
  database: mysite_test
  username: armaine
  password: afXHXRhyjP9B5rJgL6b7tjtgvm6lEqlu
  host: dpg-clh0qlb1hq4c73fb3q6g-a.singapore-postgres.render.com

production:
  <<: *default
  # Use DATABASE_URL environment variable for production
  url: <%= ENV['DATABASE_URL'] %>