default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mysite_development
  username: armaine
  password: afXHXRhyjP9B5rJgL6b7tjtgvm6lEqlu
  host: dpg-clh0qlb1hq4c73fb3q6g-a.singapore-postgres.render.com

test:
  <<: *default
  database: employees
  username: armaine
  password: JoshuaGilo820356741234
  host: localhost
  # Specify port if it's not the default PostgreSQL port (5432)
  # port: your_port

production:
  <<: *default
  # Use DATABASE_URL environment variable for production
  url: <%= ENV['DATABASE_URL'] %>